# Example Cloudflare Wrangler configuration for Astro.js

name = "gemini-proxy-worker"
compatibility_date = "2026-06-09"
compatibility_flags = [ "nodejs_compat_v2" ]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "dbdb8106d79540ebb697973b0fbb7dec"